e-test-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root 'pages#index'

  resources :profiles
  resources :categories
  resources :orders, only: [:index]
  get 'pages/showpage'
  resources :products do
    resources :posts
    resources :questions
    resources :orders, only: [:show, :new, :create, :edit, :update, :destroy]
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

e-test-master/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

e-test-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

e-test-master/app/models/categorie.rb
class Categorie < ApplicationRecord
	mount_uploader :photo, PhotoUploader
	has_many :products
#	belongs_to :admin_user
#	validates :name, :photo, presence: true
end

e-test-master/app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
    belongs_to :product
end

e-test-master/app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
    belongs_to :product
end

e-test-master/app/models/product.rb
class Product < ApplicationRecord
	mount_uploaders :images, PhotoUploader
	serialize :images, JSON # If you use SQLite, add this line.

	belongs_to :categorie
    has_many :posts
    has_many :questions
    has_many :orders
end

e-test-master/app/models/profile.rb
class Profile < ApplicationRecord
	mount_uploader :avatar, PhotoUploader

	belongs_to :user
end

e-test-master/app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
    belongs_to :product
end

e-test-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :posts
  has_many :questions
  has_many :orders
end

e-test-master/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :authenticate_user!
before_action :set_product

  def index
  	@orders = current_user.orders
  end

  def new
    @order = Order.new
  end

  def create
    params[:order][:product_id] = @product.id
    @order = current_user.orders.build(order_params)
    if @order.save
      redirect_to product_path(@product.id)
    else
      render 'new'
    end
  end

private
  def set_product
    @product = Product.find_by(id: params[:product_id])
  end

  def order_params
    params.require(:order).permit(:user_id, :product_id, :comment, :ordercount)
  end
end

e-test-master/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	if user_signed_in? and current_user.profile.nil?
  		redirect_to new_profile_path
  	end

  	@categories = Categorie.all
    @product = Product.find_by(id: params[:id])
    @product = Product.all
  	if user_signed_in?
  		@orders
    end
  end

  def showpage
    @categories = Categorie.all
  end
  def _allcategories
    @categories = Categorie.all
  end
end

e-test-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :set_product

  def new
    @comment = Post.new
  end
  
  def create
    params[:post][:product_id] = @product.id
    @comment = current_user.posts.build(post_params)
    if @comment.save
      redirect_to product_path(@product.id)
    else
      render 'new'
    end
    
  end
    
private
  def set_product
    @product = Product.find_by(id: params[:product_id])
  end
  
  def post_params
    params.require(:post).permit(:user_id, :product_id, :body)
  end
end

e-test-master/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
  	@product = Product.find_by(id: params[:id])
    @comments = @product.posts
    @questions = @product.questions
  end

end

e-test-master/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!

  def new
  	@profile = Profile.new
  end

  def create
  	@profile = current_user.build_profile(profile_params)
  	if @profile.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def show
  	@profile = Profile.find_by(id: params[:id])
  end

  def edit
  	@profile = Profile.find_by(id: params[:id])
  end

  def update
  	@profile = Profile.find_by(id: params[:id])
    if @profile.update(profile_params)
  		redirect_to profile_path(@profile.id)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @profile = Profile.find_by(id: params[:id])
  	@profile.destroy 
  	redirect_to root_path
  end

private 
  def profile_params
  	params.require(:profile).permit(:user_id, :name, :phone, :address, :avatar)
  end
end

e-test-master/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :authenticate_user!
before_action :set_product

  def new
    @question = Question.new
  end
  
  def create
    params[:question][:product_id] = @product.id
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to product_path(@product.id)
    else
      render 'new'
    end
    
  end
    
private
  def set_product
    @product = Product.find_by(id: params[:product_id])
  end
  
  def question_params
    params.require(:question).permit(:user_id, :product_id, :body)
  end
end

e-test-master/app/helpers/application_helper.rb
module ApplicationHelper
end

e-test-master/app/helpers/categories_helper.rb
module CategoriesHelper
end

e-test-master/app/helpers/orders_helper.rb
module OrdersHelper
end

e-test-master/app/helpers/pages_helper.rb
module PagesHelper
end

e-test-master/app/helpers/posts_helper.rb
module PostsHelper
end

e-test-master/app/helpers/products_helper.rb
module ProductsHelper
end

e-test-master/app/helpers/profile_helper.rb
module ProfileHelper
end

e-test-master/app/helpers/questions_helper.rb
module QuestionsHelper
end

e-test-master/app/views/products/show.html.erb
<div class="row">
  <div class="col-sm-2">	</div>
  <div class="col-sm-8">
		<h2 class="prodct">Product</h2>
			<span style="font-size: 15px;" class="textdekor"></span>
					<% @product.images.each do |image| %>
						<span style="font-size: 22px;" class="textdekor">
							<div class="categorx">
								<%= image_tag(image.url, size: "150x150", class: "imageproduct") %>
										<% end %>
										<i class="textdekor"><%= @product.name %></i>
										<i class="textdekor">Price: <%= @product.price %></i>
										<i class="textdekor">Description: <%= @product.description %></i>
										<i class="textdekor">Count of product: <%= @product.pcount %></i>
										</div>
											</span>
											<%= link_to new_product_post_path(@product.id) do %>
											<i class="textdekor">Write Comment</i><br/>
											<% end %>
											<%= link_to new_product_question_path(@product.id) do %>
											<i class="textdekor">Write Question </i><br/>
											<% end %>
											<%= link_to new_product_order_path(@product.id) do %>
											<i class="textdekor">Order a product</i><br/>
											<% end %>

											<div class="commenx">
												<% @comments.each do |comment| %>
													<div class="commenx">
														Comment: <%= comment.body %><br>
														<%= comment.user.profile.name %>
													</div>
												<% end %>
											</div>

											<div class="questionx">
												<% @questions.each do |question| %>
													<div class="questionx">
															Question: <%= question.body %><br>
															<%= question.user.profile.name %>
														</div>
												<% end %>
											</div>
		</div>
  		<div class="col-sm-2">.col</div>
</div>

e-test-master/app/views/profiles/edit.html.erb
<div class="profile-body">
  <div class="profile-form">
    <h1>Edit Profile</h1>
<%= form_for @profile, url: profile_path(current_user.id) do |f| %>
  <div class="profile-edit-views">
    <div>
   <%= f.label :name,'Name', class: 'form-label'%><%= f.text_field :name, class:'profile-field' %><br />
  </div>
  <div>
   <%= f.label :phone, 'Phone', class: 'form-label'%><%= f.text_field :phone, class:'profile-field' %><br />
  </div>
  <div>
   <%= f.label :address, 'Address', class: 'form-label'%><%= f.text_field :address, class:'profile-field' %><br />
  </div>
  <div>
   <%= f.label :avatar, 'Avatar', class: 'form-label'%><%= f.file_field :avatar, class:'avatar-for-profile' %><br />
  </div>
    <%= f.submit "Update", class:'button-edit-profile' %>
</div>
<% end %>
</div>
</div>

e-test-master/app/views/profiles/new.html.erb
<div class="profile-body">
<%= form_for @profile, url: profiles_path do |f| %>
  Name: <%= f.text_field :name %><br />
  Phone: <%= f.text_field :phone %><br />
  Address: <%= f.text_field :address %><br />
  Avatar: <%= f.file_field :avatar %><br />
  <%= f.submit "Create" %>
<% end %>
</div>

e-test-master/app/views/profiles/show.html.erb
<div class="profile-body-show">
  <div class="profile-show-views">
    <%= link_to edit_profile_path(current_user.id), class: 'link-to-profile-edit' do%>
    <i class="fas fa-edit" style="color: #373D42"></i>
    <% end %><br />
    <%= image_tag current_user.profile.avatar_url, class:'photoprofile' %>
      <div class="profile-info">
        <h2>
        <%= label :name,'Name', class: 'form-label'%><%= current_user.profile.name %><br />
      </h2>
        <h6>
        <%= label :phone,'Phone', class: 'form-label'%><%= current_user.profile.phone%><br />
      </h6>
        <h6>
        <%= label :address,'Address', class: 'form-label'%><%= current_user.profile.address %><br />
      </h6>
      </div>
  </div>
</div>

e-test-master/app/views/questions/new.html.erb
<div class="question">
<%= form_for @question, url: product_questions_path(@product.id) do |f| %>
  Question: <%= f.text_area :body, size: "30x10" %><br />
  <%= f.submit "Create" %>
<% end %>
</div>